FROM python:3.11-alpine AS builder
RUN apk add --no-cache build-base python3-dev
WORKDIR /app
COPY abb_app.py .

FROM python:3.11-alpine
WORKDIR /app
COPY --from=builder /app/abb_app.py .

CMD ["python", "abb_app.py"]
