FROM python:3.11-alpine AS builder
RUN apk add --no-cache build-base python3-dev
WORKDIR /app
COPY sdf_app.py .

FROM python:3.11-alpine
WORKDIR /app
COPY --from=builder /app/sdf_app.py .

CMD ["python", "sdf_app.py"]
