FROM python:3.11-alpine AS builder
RUN apk add --no-cache build-base python3-dev
WORKDIR /app
COPY xyz_app.py .

FROM python:3.11-alpine
WORKDIR /app
COPY --from=builder /app/xyz_app.py .

CMD ["python", "xyz_app.py"]


